# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
# avoid duplicate tests in PRs
branches:
  only:
    - master
os:
  - linux
#  - osx
julia:
  - 1
# matrix:
#  allow_failures:
#    - julia: nightly
env:
  - GROUP=Layers
  - GROUP=BasicNeuralDE
  - GROUP=AdvancedNeuralDE
  - GROUP=Integration
notifications:
  email: false
after_success:
  # push coverage results to Coveralls
  - julia -e 'import Pkg; cd(Pkg.dir("DiffEqFlux")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'import Pkg; cd(Pkg.dir("DiffEqFlux")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
